language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"

gemfile: .gemfile
sudo: false
notifications:
  email:
    - al@lab42.it
